version: '2'
services:
  sfserver:
    image: akaronte/sfserver:latest
    container_name: sfserver
    user: "sfserver:sfserver"
    volumes:
      - ./SATISFACTORY:/home/sfserver
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
      - 7777:7777/tcp
    restart: always
